---
title: "forecast_Project1"
author: "Caroline Vickery"
date: "2024-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, echo = F, warning=F, message=F}
#install.packages('remotes')
#install.packages('fpp3') # package for applying simple forecasting methods
#install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
#nstall.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
#install.packages('lubridate') # working with dates and times
#remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission
# update.packages(ask = FALSE)
# Load packages
library(tidyverse)
library(lubridate)

set.seed(101)
```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'temperature')
```


```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

variables <- c("air_temperature", "relative_humidity", "eastward_wind", "northward_wind")
#Other variable names can be found at https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  # convert air temp to C
  mutate(air_temperature = air_temperature - 273.15)

noaa_past_mean$windspeed<-sqrt(noaa_past_mean$eastward_wind^2 + noaa_past_mean$northward_wind^2)


```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(1)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))
variables <- c("air_temperature", "relative_humidity", "eastward_wind", "northward_wind")

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% variables) |> 
  collect()

noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) |>
  # convert to Celsius
  mutate(air_temperature = air_temperature - 273.15) 

noaa_future_daily$windspeed<-sqrt(noaa_future_daily$eastward_wind^2 + noaa_future_daily$northward_wind^2)

combined_met_df1 <- bind_rows(noaa_past_mean, noaa_future_daily)

jasontest<-combined_met_df1 %>% 
  arrange(site_id, parameter, datetime) %>% 
  group_by(site_id, parameter) %>%
  mutate(airtemp_1daylag = lag(air_temperature)) #correct way to lag 
jasontest$datetime_lagged<-jasontest$datetime - days(1)
derulotest<-jasontest

#filling in the gaps - Sys.Date data is missing airtemp_1daylag
cyrus_df<-NULL


for(i in 1:length(lake_sites$field_site_id)){
  curr_site <- lake_sites$field_site_id[i]
  
  currentrow<-derulotest %>% filter(datetime==Sys.Date(),
                site_id==curr_site,
                airtemp_1daylag!=is.na(airtemp_1daylag))
  
  airtemptopaste<-currentrow$airtemp_1daylag #yesterday's measured air temp

  mileytest<-derulotest %>% filter(datetime==Sys.Date(),
                                 site_id==curr_site) %>% 
    select(datetime, site_id, parameter, airtemp_1daylag, datetime_lagged)

  party<-mileytest %>% filter(parameter>=0)
  
  party$airtemp_1daylag<-airtemptopaste
  #party$realdatetime<-realdatetopaste
  
  cyrus_df<-dplyr::bind_rows(party, cyrus_df)
}


derulotest2<-left_join(derulotest, cyrus_df, by=c("datetime", "site_id", "parameter", "datetime_lagged")) 

derulotest2<-derulotest2 %>% select(order(colnames(.))) %>% unite("airtemp_1daylag", airtemp_1daylag.x:airtemp_1daylag.y, na.rm = TRUE, remove = FALSE)

derulotest2<-derulotest2 %>% select(-c(airtemp_1daylag.x, airtemp_1daylag.y))

derulotest2$airtemp_1daylag<-as.numeric(derulotest2$airtemp_1daylag)
```

```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  filter(variable == 'temperature') |>
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  right_join(derulotest2, 
            by = c("datetime","site_id"))

```

```{r forecast-loop with uncertainty}

forecast_horizon <- 30
forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 30

forecast_df <- NULL
###NEXT STEP: REMOVE NAs FROM MOD WITHOUT CREATING ALL NAs
for(i in 1:length(lake_sites$field_site_id)) {  
  
  #curr_site <- lake_sites$field_site_id[i]
  curr_site<-"BARC"
  # Get only the necessary data for the specific site
  site_target <- targets_lm |>
    filter(site_id == curr_site,
           datetime <= ymd(forecast_date),
           is.na(parameter))
  
  site_target2<- site_target  %>% 
  arrange(site_id, parameter, datetime) %>% 
  group_by(site_id, parameter) %>%
  mutate(watertemp_1daylag = lag(temperature))

  noaa_future_site <- derulotest2 |> 
    filter(site_id == curr_site,
           datetime >= ymd(forecast_date), 
           parameter != is.na(parameter)) %>%
  mutate(watertemp_1daylag = NA)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b
  fit <- lm(site_target2$temperature ~ site_target2$airtemp_1daylag + site_target2$relative_humidity + site_target2$watertemp_1daylag)
    
  #parameter uncertainty  
  summary_fit<-summary(fit)
coeffs <- round(fit$coefficients, 3)

params_se <- summary_fit$coefficients[,2]

param_df <- data.frame(beta1 = rnorm(n_members, coeffs[1], params_se[1]),
                       beta2 = rnorm(n_members, coeffs[2], params_se[2]),
                       beta3 = rnorm(n_members, coeffs[3], params_se[3]), 
                       beta4 = rnorm(n_members, coeffs[4]))

#process uncertainty
mod <- predict(fit, site_target2)
residuals <- mod - site_target2$temperature

sigma <- sd(residuals, na.rm = TRUE) # Process Uncertainty Noise Std Dev.; this is your sigma

#attempt to backcast
site_target2_todaylag<-site_target2  %>% filter(temperature!=is.na(temperature)) %>%  slice(which.max(as.Date(datetime, '%m/%d/%Y')))

backcast_dates<-seq(from = ymd(site_target2_todaylag$datetime) +1, to = ymd(forecast_date), by = "day")


site_target2$rownumber<-c(1:nrow(site_target2))


  if (site_target2_todaylag$watertemp_1daylag!=Sys.Date()) {
    for (j in 1:length(backcast_dates)){
      
      site_drivers_back <- site_target2 %>%
    filter(datetime == backcast_dates[j])
      
      currentrow<-site_target2 %>%
    filter(datetime == backcast_dates[j]) %>% 
        select(c("rownumber", "site_id", "parameter"))
      
      backcast_temp <- fit$coefficients[1] + 
        fit$coefficients[2] * site_drivers_back$airtemp_1daylag +
        site_drivers_back$relative_humidity * fit$coefficients[3] +
        site_drivers_back$watertemp_1daylag * fit$coefficients[4]
      
      site_target2$temperature[currentrow$rownumber]<-backcast_temp
      
      site_target2<- site_target2  %>% 
        mutate(watertemp_1daylag = lag(temperature))
    }
  }

firstfuture<-site_target2 %>% filter(datetime==Sys.Date()) %>% select(watertemp_1daylag, site_id, parameter)
firstfuturetopaste<-firstfuture$watertemp_1daylag
noaa_future_site$rownumber<-c(1:nrow(noaa_future_site))

currentrow2<-noaa_future_site %>%
    filter(datetime == Sys.Date()) %>% 
        select(c("rownumber", "site_id", "parameter", "datetime"))
currentrow2<-as.vector(currentrow2$rownumber)

for(v in currentrow2){
  noaa_future_site$watertemp_1daylag[v]<-firstfuturetopaste
} ###THIS IS NOT FILLING IN ALL THE ROWS, JUST THE FIRST. NEED TO INSERT THESE VALUES INTO ALL ROWS 


  # Loop through all forecast dates
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
    noaa_future_site$temp_prediction<-NA
    
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t]) 
  
  # use linear regression to forecast water temperature for each ensemble member
  forecasted_temperature <- param_df$beta1 + param_df$beta2 * site_drivers$airtemp_1daylag + site_drivers$relative_humidity * param_df$beta3 + site_drivers$watertemp_1daylag * param_df$beta4 + rnorm(n_members, mean = 0, sd = sigma)
  
  # put all the relevant information into a tibble that we can bind together
  curr_site_df <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = curr_site,
                         parameter = 1:n_members,
                         prediction = forecasted_temperature,
                         variable = "temperature") 
  
  forecast_df <- dplyr::bind_rows(forecast_df, curr_site_df)
  
  
  
  
  
##CAN I PREDICT THE FORECASTED TEMPERATURES USING THE OTHER VARIABLES, THEN CREATE A SECOND FORECAST USING THE LAGGED WATER TEMPERATURE?
  #I have 30 forecasted temperatures for one date with 30 parameters. I need to select those 30 rows from noaa_futre_site and insert those 30 forecasted temperatures. 

  #feeding the next loop run 
  currentrow3<-as.vector(site_drivers$rownumber)
  
creatingspace<-NULL
for(m in currentrow3){
  current_noaa_future_site<-noaa_future_site %>%
    filter(rownumber==m)
  
  creatingspace<-dplyr::bind_rows(current_noaa_future_site, creatingspace)
  #noaa_future_site$temp_prediction[m]<-forecasted_temperature
}

filledspace<-NULL
for(u in 1:nrow(curr_site_df)){
  forecasttopaste<-curr_site_df$prediction[u]
  parameterforfilter<-curr_site_df$parameter[u]
  
  creatingspace2<-creatingspace %>%  filter(parameter==parameterforfilter) 
    creatingspace2$temp_prediction<-forecasttopaste
  
  filledspace<-dplyr::bind_rows(filledspace, creatingspace2)
    }

binders<-noaa_future_site %>% select(-c(temp_prediction)) %>% colnames()

noaa_future_site<-left_join(noaa_future_site, filledspace, 
                            by=binders)

noaa_future_site<-noaa_future_site %>% select(order(colnames(.))) %>% unite("temp_prediction", temp_prediction.x:temp_prediction.y, na.rm = TRUE, remove = FALSE)

noaa_future_site<-noaa_future_site %>% select(-c(temp_prediction.x, temp_prediction.y))

noaa_future_site$temp_prediction<-as.numeric(noaa_future_site$temp_prediction)

   noaa_future_site<- noaa_future_site  %>% 
         mutate(watertemp_1daylag = lag(temp_prediction))
  
  

  
  }
  
  message(curr_site, 'forecast run')
}

```

```{r make-standard}
# Make forecast fit the EFI standards
# Remember to change the model_id when you make changes to the model structure!
my_model_id <- 'Vickery_project1'

forecast_df_EFI <- forecast_df %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter)) %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

```

```{r plot-forecast}
forecast_df_EFI |> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', forecast_df_EFI$variable[1], ' on ', forecast_df_EFI$reference_datetime[1]))
```

WRITE TEXT DESCRIPTION OF WHAT YOU DID DOWN HERE
